### PR TITLE
Last GSoC features (see description)

### PR DESCRIPTION
**Pull request by AdrianBZG**
This is the last pull request to submit the project for GSoC final evaluation:

1. Fixing extra filters being added on Proteins view (issue #70)
2. Table is now using dashboard to add Save As, Export and Generate functionalities to it (issue #16)
3. Code refactoring and cleaning

### CODE REVIEW

**Comment by AdrianBZG** [comment]
@yochannah Should be good now! :+1: 

image

**Comment by yochannah** [comment]
98% ;) also the double arrows in the dropdowns - to the right of 'save as
list' and 'generate python code' :) there ideally should be only 1

**Comment by yochannah** [comment]
Perfect!

**Comment by AdrianBZG** [comment]
@yochannah Now should be ok, weird things happening because of style replacement :laughing: 

image

**Pull request merged**
