### PR TITLE
Add scroll to top button to web page

### PR DESCRIPTION
**Pull request by Emuohwo**
## Description
Describe the changes made and why they were made.
Added a container in footer.pug for the scroll to top button: this is the container where the scroll button is located.
Added js code for the button to common.js: I want to button to trigger when a user scroll to a certain level downward
I did the styling of the button in _global.scss: This is to give the button a good look
## Related issues and discussion
#90

## Screenshots, if any
This is the look on small screen
image
On a bigger screen
image

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ x] Run the tests

### CODE REVIEW

**Comment by Emuohwo** [comment]
@AdrianBZG  @Nikhil-Vats Kindly review Pull Request for issue #90

**Comment by Nikhil-Vats** [comment]
Nice work @Emuohwo. Everything works as expected. 💯 👍 🎉 

I think [this](https://github.com/intermine/InterMine-Data-Browser-Tool/blob/deb5478f3b36faabd48f102196c29c64ceb03b18/src/scss/_global.scss#L122) class is not used anywhere and can be removed. @AdrianBZG what do you think?

**Comment by AdrianBZG** [comment]
Hi @Emuohwo ,

Nice work, if you could address the issue pointed by @Nikhil-Vats (increase bottom to 40px), we'd happy to accept this PR 😄

**Comment by Emuohwo** [comment]
@Nikhil-Vats  and @AdrianBZG consider it done.

**Comment by Emuohwo** [comment]
@Nikhil-Vats  and @AdrianBZG the scroll button still covered part of the footer content even after I have increase bottom to `40px`
image
I now increase the bottom to `50px` and added a media query of `max-width: 600px` and set it to `75px`. here's what I got
image

image
Should I continue with your recommendation or I should use the 50px and media query. What do you advice?

**Comment by Nikhil-Vats** [comment]
@Emuohwo Nice work on the media query! 🎉 💯 
Can you change the media-query from `max-width:600px` to `max-width:785px`, it would look better that way?

**Comment by Emuohwo** [comment]
@Nikhil-Vats I have increased the width to 785px for the media query.

**Comment by Nikhil-Vats** [comment]
@Emuohwo Good work! 💯

**Pull request merged**
