### PR TITLE
Place back missing mines filters config

### PR DESCRIPTION
**Pull request by AdrianBZG**

### CODE REVIEW

**Comment by yochannah** [comment]
@AdrianBZG When I check this out, run npm install, then run npm start,  I get a blank UI and a console error - did I miss a step?

image

**Comment by AdrianBZG** [comment]
@yochannah Do you have any error on server console?

**Comment by yochannah** [comment]
Nope, just a bunch of successful GETs

```bash
[11:57:03] Starting 'default'...
[11:57:03] Finished 'default' after 1.33 μs
GET / 304 279.155 ms - -
GET /vendor/font-awesome/css/font-awesome.min.css 200 5.008 ms - 31000
GET /stylesheets/data-browser-style-main.css 200 46.564 ms - 16568
GET /javascripts/utils.min.js 200 6.135 ms - 2386
GET /javascripts/request-handler.min.js 200 6.737 ms - 3528
GET /javascripts/common.min.js 200 7.470 ms - 43181
GET /javascripts/main-view.min.js 200 7.308 ms - 6694
GET /vendor/chart.js/Chart.min.js 200 5.947 ms - 157843
GET /javascripts/sidebar-events.min.js 200 5.512 ms - 1919
GET /javascripts/piechart-events.min.js 200 7.080 ms - 223
GET /img/intermine-logo.png 200 3.830 ms - 5346
GET /img/favicon.ico - - ms - -
GET /mine_configs/mines_config.json 200 3.111 ms - 3437

```

**Comment by AdrianBZG** [comment]
@yochannah mmmm, I tried with a fresh git clone, did npm install and npm start, and worked, maybe re-clone ??

**Comment by yochannah** [comment]
Still the same for me. Could it be some global dependency you have? I've just tried to deploy it here - http://staging-data-browser.apps.intermine.org does it work for you?

**Comment by AdrianBZG** [comment]
That deployment is not working for me, what I did was, in the project folder, in this order:
npm install gulp
npm install
npm start

**Comment by yochannah** [comment]
hmmmm, do me a favour and delete your local storage, then see if it still works? It might be this line:

https://github.com/intermine/InterMine-Data-Browser-Tool/blob/master/src/js/common.js#L1476

**Pull request merged**
