### PR TITLE
Fixed issue #35 

### PR DESCRIPTION
**Pull request by VarunBhandia**
I have fixed [mine dropdown - clicking on the arrow doesn't work #35
](https://github.com/intermine/InterMine-Data-Browser-Tool/issues/35) . Please review my changes.

### CODE REVIEW

**Comment by yochannah** [comment]
@VarunBhandia could you check the file in not-minified? right now it's very hard to see what has changed. Thanks!

**Comment by VarunBhandia** [comment]
Screenshot from 2019-03-20 10-06-54
Have only changed the .form-control width from 200px to 180px.

**Comment by yochannah** [comment]
@VarunBhandia take a look at the diff for your PR: https://github.com/intermine/InterMine-Data-Browser-Tool/pull/37/files green is new code, red is deleted code. Maybe you have an editor that automatically minifies things?

**Comment by VarunBhandia** [comment]
@yochannah ma'am I have created a new PR #38  I hope that will be work. Thanks

**Comment by yochannah** [comment]
Thanks @VarunBhandia! I'll close this PR.

**Pull request closed without merging**
