### PR TITLE
Phenotype filter

### PR DESCRIPTION
**Pull request by LakshSingla**
Most of the part of adding the Phenotype filter is complete except these:
 - Phenotype onstraints are not being added to the im-tables properly. I am unable to find the docs of im-tables
- Commenting the code so as to keep it consistent with the codebase

Reference #21

### CODE REVIEW

**Comment by AdrianBZG** [comment]
Hi @LakshSingla , can you please tell me what are you missing to make the code add the constraint to the table so I can help you?

**Comment by LakshSingla** [comment]
Alright, so lemme walk you through what I did: 
 1. Created an express route [here](https://github.com/LakshSingla/InterMine-Data-Browser-Tool/blob/a3884c0b12b9d26cd6d69a981e59264722791c20/routes/fetch.js#L390-L415) to fetch the data based on Phenotype
 2. Added a method to fetch that data here [here](https://github.com/LakshSingla/InterMine-Data-Browser-Tool/blob/a3884c0b12b9d26cd6d69a981e59264722791c20/src/js/request-handler.js#L263-L272)
 3. Added the corresponding handler on the left hand sidebar [here](https://github.com/LakshSingla/InterMine-Data-Browser-Tool/blob/a3884c0b12b9d26cd6d69a981e59264722791c20/src/js/common.js#L1207-L1258) and added the markup for the filter itself [here](https://github.com/LakshSingla/InterMine-Data-Browser-Tool/blob/a3884c0b12b9d26cd6d69a981e59264722791c20/views/includes/navbar.pug#L47-L56).
Here is the result of above task (cropped up part)
screenshot from 2019-02-05 18-02-21

Now I can't figure out how to actually add the constraint on the table if a user clicks a Phenotype term (I am unable to find the exact name of the constraint). It would be really great if you could help me out :smile:

**Comment by LakshSingla** [comment]
Apart from that, here is the query that I am using: 
```
    var query = {
        "from": "HPOTerm" ,
        "select": ["identifier", "name", "ontology.name", "description"],
        "model": {
            "name": "genomic"
        },
        "orderBy": [{
            "path": "identifier",
            "direction": "ASC"
        }]
    };
```

I was trying to add the constraint to the tables using following snippet. Is this constraint correct ?? I am unable to find the documentation for `im-tables`.
`window.imTableConstraint["phenotypeName"].push(ui.item.value);`

In the issue, the solution you proposed involved fetching the table again. Should I create a new view (like Gene, Protein) to achieve that or modify the existing Protein view?

**Comment by yochannah** [comment]
Hey @LakshSingla ! 

I actually have an example for this - sorry, the repo has broken links so I haven't shared it publicly. Does this help? https://yochannah.github.io/im-tables-examples/constraint-add.html

**Comment by LakshSingla** [comment]
@yochannah The link shows for GO Annotations. Is there anyone with Phenotypes or HPOTerm?

**Comment by AdrianBZG** [comment]
@LakshSingla For more clarification, here is an example of showing the gene list filtering with a specific value for phenotypes (hpoTerm.name):

```
var imtables = require('imtables');

var selector = '#some-elem';
var service  = {root: 'http://www.humanmine.org/humanmine/service/'};
var query    = {
  "from": "Gene",
  "select": [
    "symbol",
    "name",
    "primaryIdentifier",
    "secondaryIdentifier",
    "organism.name",
    "diseases.hpoAnnotations.hpoTerm.name"
  ],
  "orderBy": [
    {
      "path": "symbol",
      "direction": "ASC"
    }
  ],
  "where": [
    {
      "path": "diseases.hpoAnnotations.hpoTerm.name",
      "op": "=",
      "value": "Alzheimer disease",
      "code": "A"
    }
  ]
};

imtables.loadTable(
  selector, // Can also be an element, or a jQuery object.
  {"start":0,"size":25}, // May be null
  {service: service, query: query} // May be an imjs.Query
).then(
  function (table) { console.log('Table loaded', table); },
  function (error) { console.error('Could not load table', error); }
);
```

**Comment by LakshSingla** [comment]
@AdrianBZG Thanks a lot!!! But I am wondering isn't there any way to fetch all the table data at once and then update it based on the constraints specified, as done in pathways filter ???
Still, thanks a lot for your help, I will get back to you with the update tonight

**Comment by LakshSingla** [comment]
@AdrianBZG The disease filter is now working, however minor details  have to be smoothed out:

 - Change the filter name from `Phenotype Name` to `Disease Name` 
 - Add the icon for it in the sidebar 
 - I guess this filter is custom for HumanMines (like rest of the filters), as mines such as maize mines do not support this filter. Hence, make this filter a custom one (as for the rest of the filters).

Please suggest for the first 2 tasks, while I figure out the third one.

**Comment by AdrianBZG** [comment]
@LakshSingla The name should be "Phenotype Name", as it's different from Disease Name, because even tho there looks like that there are names of disease, they are depicting different things.

What about this icon: https://fontawesome.com/icons/product-hunt?style=brands? P of Phenotype.

Yes, it's a custom one, so it should be added to the custom filters check part, and then added in the custom_filters JSON file for HumanMine: https://github.com/intermine/InterMine-Data-Browser-Tool/blob/master/src/mine_configs/mines_config.json. It also should use the query from that file, and not from the code (as that custom filters are already doing)

**Comment by LakshSingla** [comment]
@AdrianBZG I have made the Phenotype filter a custom one. Please review this PR :)).

**Comment by AdrianBZG** [comment]
@LakshSingla It works! Good job :smile: :+1:

**Pull request merged**
