### PR TITLE
Fixed footer

### LINKED ISSUE #56: Footer text moves out of the box in some devices
The text in the footer moves out of the container on some of the defined screen sizes. Here's the screenshot for the issue:

Footer

### PR DESCRIPTION
**Pull request by dmahajan980**
Fixes #56 

footer1

footer2

### CODE REVIEW

**Comment by AdrianBZG** [comment]
Hi @dmahajan980 ,

The style should be changed in the CSS in the src directory instead of the serving directory (/public). Could you please make the change?

Thanks 😄

**Comment by dmahajan980** [comment]
Whoops! Sorry for that @AdrianBZG . Will fix that and send the PR as soon as possible.

**Comment by dmahajan980** [comment]
@AdrianBZG I have made the changes as said. Please review it and let me know if there's anything wrong.

**Comment by AdrianBZG** [comment]
Hi @dmahajan980 ,

It looks like now part of the app has lost the background color and it's now gray, see:

image

**Comment by AdrianBZG** [comment]
I also got Error: Cannot find module 'es6-promise' when trying to npm start afte npm install.

**Comment by dmahajan980** [comment]
Sorry for generating these errors. Will fix all of it and send a new PR. 
Also, **es6-promise** has been added to dependencies in commit #59. I am not sure why that error is generated. I'll check it out

**Comment by dmahajan980** [comment]
@AdrianBZG I have sent another PR #61 which fixes #56 considering everything discussed till now. Please close this pull request and review #61.

Thanks

**Comment by dmahajan980** [comment]
@AdrianBZG I have sent another PR #61 which fixes #56 considering everything discussed till now. Kindly close this pull request and review #61.

Thanks

**Comment by dmahajan980** [comment]
@AdrianBZG I have sent another PR #61 which fixes #56 considering everything discussed till now. Please close this pull request and kindly review #61.

Thanks

**Comment by AdrianBZG** [comment]
Closed as author requested, moving to #61

**Pull request closed without merging**
