### PR TITLE
Preloader added

### PR DESCRIPTION
**Pull request by Zemotacqy**
I have added the preloaders wherever I could find a request being made in the code. However I had to do inline styling because some how in the src/css/hmb-style-main.css the styling added by me was not being reflected in the web page.

### CODE REVIEW

**Comment by AdrianBZG** [comment]
Looking good @Zemotacqy -- perhaps we could improve it a little bit more: what about avoiding the inline styling by adding it to the SASS files, that get compiled afterwards by gulp in the form of CSS? (https://github.com/intermine/InterMine-Data-Browser-Tool/tree/master/src/scss)

**Comment by Zemotacqy** [comment]
On it.

**Comment by Zemotacqy** [comment]
I have removed the inline styling and placed it in src/scss/_global.scss file.

**Comment by AdrianBZG** [comment]
Hi @Zemotacqy ,

It looks like there is some problem with the implementation. After going to the tool, I see a grey background with a loading animation, then the animation goes away but the grey background stays there, and I don't see anything:

image

Server console shows:

image

Is it working on your system?

**Comment by Zemotacqy** [comment]
@AdrianBZG I am also getting this kind of error but since its error code is 504 so it must be a server side error, I think

**Comment by AdrianBZG** [comment]
@Zemotacqy but is the browser to you? I only see a grey screen when the loading animation goes away

**Comment by Zemotacqy** [comment]
@AdrianBZG I just checked, There is a problem in my latest commit, when i reverted back to my previous commit, Its working perfectly fine. I will again do the removal of inline styling part and notify you. If its ok with you?

**Comment by Zemotacqy** [comment]
I have fixed the bug @AdrianBZG

**Comment by Zemotacqy** [comment]
Hello @AdrianBZG , sorry I am a bit late, as you can see I have completed the second part. For the first part though I have some Doubts. From what I can see, there are 3 js files which handle the display and API triggering, src/js/common.js, main-view.js, request-handler.js. request-handler.js only manages the ajax requests, so if there is any error(we can catch it there itself [for preloader] and hide it). Now I am confused in main-view.js and common.js. Both these files handle the buttons like (GO!) and reset. Some functions handle that part where there is no button (like auto-complete) or the "organism short name" filter.
Point being I am unable to find a single block of code which sends a request and handles the error part. So I have to do for each filter separately or is there a function which I may have missed(Question 1)?
The NO_RESPONSE error, where is it handled, in which function, I am unable to find a single function for that(Question 2)?
Thanks for your responses, they really help me a lot:smiley:

**Comment by Zemotacqy** [comment]
@AdrianBZG I gave another try and all my doubts were cleared. I have added preloaders to each filter. Please let me know if there are any changes.

**Comment by AdrianBZG** [comment]
Hi @Zemotacqy , It looks that the preloader animation almost instantly disappears when using a filter, without waiting for the table to be loaded. For instance, if I filter by Location: Chromosome 12, Start 1, End 100000000, the loading animation appears but then it goes straightaway.

**Comment by AdrianBZG** [comment]
@Zemotacqy for what I can see, the reason it's potentially related with the fact that you are doing a hidePreloader(); everytime you push a constraint to the constraints array, and this is wrong, as that method should be called once the table has loaded (see the onRenredered event: https://github.com/intermine/InterMine-Data-Browser-Tool/blob/master/src/js/main-view.js#L49)

**Comment by Zemotacqy** [comment]
Hi @AdrianBZG , I agree with you. I have tried putting the hidePreLoader() function in [this line](https://github.com/intermine/InterMine-Data-Browser-Tool/blob/master/src/js/main-view.js#L49) and for the first time the page loads it works fine. 
Now there are two more functions inside the onTableRendered method i.e. updateElements and updateGeneLengthChart. From what I have tried, updateElements updates the table and updateGeneLengthChart updates the Pie chart. Now both these functions make ajax requests, and no matter where I call the hidePreloader function:
1. [onTableRendered](https://github.com/intermine/InterMine-Data-Browser-Tool/blob/master/src/js/main-view.js#L49) : It dissappears and Loading Table progressbar and PieChart are still not loaded. 
2. [after Update Elements](https://github.com/intermine/InterMine-Data-Browser-Tool/blob/master/src/js/common.js#L1405)
3. [after PieChart Updates](https://github.com/intermine/InterMine-Data-Browser-Tool/blob/master/src/js/common.js#L1682) 
For 2nd and 3rd choice, the preloader disappears depending upon the connection. Whichever loads first.
Moreover, it seems like [this line](https://github.com/intermine/InterMine-Data-Browser-Tool/blob/master/src/js/main-view.js#L49) is being hit more than once whenever a filter a applied. Please tell which option is the best one. Is there a more better approach? 
Thanks

**Comment by Zemotacqy** [comment]
I dived further into the issue and found that functions like "readTextFile" and "escapeMineUrl" are giving me errors. These functions don't have any declaration in the code. It would be nice if you could confirm that compiling of ES6 was correct or Do I need to edit it further.

**Comment by AdrianBZG** [comment]
Closing this due to inactivity, please feel free to pick it up again when you find some time.

**Pull request closed without merging**
